apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Deploys the GlusterFS container
    labels:
      template: gluster
    name: gluster
  spec:
    replicas: 1
    selector:
      name: gluster
    template:
      metadata:
        labels:
          name: gluster
        name: gluster
      spec:
        containers:
        - image: gluster/gluster-centos
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - systemctl status glusterd.service
          name: gluster
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - systemctl status glusterd.service
          securityContext:
            capabilities: {}
            privileged: true
          volumeMounts:
          - mountPath: /etc/glusterfs
            name: gluster-etc
          - mountPath: /var/log/glusterfs
            name: gluster-logs
          - mountPath: /var/lib/glusterd
            name: gluster-config
          - mountPath: /dev
            name: gluster-dev
          - mountPath: /sys/fs/cgroup
            name: gluster-cgroup
        nodeSelector:
          kubernetes.io/hostname: node-1
        volumes:
        - hostPath:
            path: /etc/glusterfs
          name: gluster-etc
        - hostPath:
            path: /var/log/glusterfs
          name: gluster-logs
        - hostPath:
            path: /var/lib/glusterd
          name: gluster-config
        - hostPath:
            path: /dev
          name: gluster-dev
        - hostPath:
            path: /sys/fs/cgroup
          name: gluster-cgroup
      strategy:
        type: Replace
      triggers:
      - type: ConfigChange
kind: List
metadata: {}
